use_frameworks!

platform :ios, '8.0'

target 'HDNOCFoundationGarbage_Example' do
  pod 'HDNOCFoundationGarbage', :path => '../'

  target 'HDNOCFoundationGarbage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
